version = 1
SPDX-PackageName = "wake-core"
SPDX-PackageDownloadLocation = "https://github.com/skaphos/wake-core"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Skaphos"
SPDX-License-Identifier = "MIT"
